function selftest_constructor()
% Synthetic constructor test, no real plant data and no optimizer.
I=struct('prvc_num',2,'prvcstr',["P01";"P02"],'units_generation_VC',[100 .8 300 250 .7;100 .4 120 400 .35], ...
 'provinceUnitRanges',[1 1;2 2],'volume',[100;100],'wind_power',zeros(2,2),'photo_power',zeros(2,2), ...
 'hydro_power',zeros(2,2),'nuclear_power',zeros(2,2),'load_power',ones(2,2)*30,'minvolume',zeros(2,2));
net=struct('A',sparse([1;-1]),'Acapacity',20);P=struct('time_num',24,'lambda',1.5,'rampRate',.6,'penalty',1e6);
c=struct('profileID',1,'year',2020,'variant','synthetic','CQ','CQ2','FL_SC',0,'ATCrate',1,'CarbonPrice',100, ...
 'etsActive',true,'carbonMode','BUY_PREMIUM_NATIONAL_ANNUAL','settlementScope','national_annual', ...
 'buyMultiplier',1,'annualDeficitPremium',0,'variableOmAdder',0,'carbonInternalization',1,'drFraction',0, ...
 'useRamping',true,'timeStepHours',1,'slackMode','SI_LINEAR_SLACK','slackFreeBandFraction',0,'networkMode','BIDIR');
[m,L,~]=pcv3_build_lp(I,P,net,c,2);assert(abs(m.obj(1)-240)<1e-10&&abs(m.obj(2)-395)<1e-10&&L.carbonAnnualRow==0);
c.buyMultiplier=1.5;c.annualDeficitPremium=.5;[m,L,~]=pcv3_build_lp(I,P,net,c,2);assert(m.obj(end)==50&&L.carbonAnnualRow>0);
fprintf('PUBLIC_CONSTRUCTOR_SELFTEST_OK=1\nSOLVER_CALLED=0\n');
end
